apiVersion: v1
kind: Secret
metadata:
  name: {{ template "emx2.fullname" . }}-postgres
  labels:
    app: {{ template "emx2.name" . }}
    chart: {{ template "emx2.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgrespassword: {{ .Values.postgres.password | b64enc | quote }}