apiVersion: v1
kind: Secret
metadata:
  name: {{ template "emx2.fullname" . }}
  labels:
    app: {{ template "emx2.name" . }}
    chart: {{ template "emx2.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  adminpassword: {{ .Values.adminPassword | b64enc | quote }}
  databasepassword: {{ .Values.database.password | b64enc | quote }}
